name: Build and Deploy API Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "api/**" # Este flujo se ejecuta solo si hay cambios en la carpeta 'api'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for API
        run: |
          docker build -t myusername/my-api ./api

      - name: Push Docker image for API to Docker Hub
        run: |
          docker push myusername/my-api
