name: Build and Run API Container Locally

on:
  push:
    branches: [ main ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      # 1) Bajar el código
      - uses: actions/checkout@v2

      # 2) Setup Java 21 (Temurin)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      # 3) Compilar Spring Boot en api/
      - name: Package API
        working-directory: api
        run: mvn clean package -DskipTests

      # 4) Configurar Buildx
      - uses: docker/setup-buildx-action@v2

      # 5) Construir la imagen localmente (sin push)
      - name: Build Docker image
        run: |
          docker build \
            --file api/Dockerfile \
            --tag api-local:latest \
            api

      # 6) Levantar el contenedor en el runner
      - name: Run API container
        run: |
          docker run -d --name api-test -p 8080:8080 api-local:latest

      # 7) Hacer un simple “health check”
      - name: Smoke test
        run: |
          for i in {1..10}; do
            if curl -fs http://localhost:8080/actuator/health | grep UP; then
              echo "✅ API is healthy" && exit 0
            fi
            echo "Waiting for API… ($i/10)"
            sleep 5
          done
          echo "❌ API did not start in time" && exit 1

 





