name: Construir imagen Docker de la API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir la imagen Docker de la API
        run: |
          docker build -t myusername/my-api ./api

      - name: Subir la imagen Docker de la API a Docker Hub
        run: |
          docker push myusername/my-api





