name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3 # Acción oficial de GitHub para extraer tu repo :contentReference[oaicite:0]{index=0

      # 2. Configurar Buildx (Builder Docker avanzado)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Setup Buildx para poder usar Docker BuildKit :contentReference[oaicite:1]{index=1}

      # 3. Log in en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construir imagen usando el Dockerfile de frontend/
      - name: Build Docker image for Frontend
        run: |
          docker build \
            --file frontend/Dockerfile \
            --build-arg NODE_ENV=production \
            --tag robertorg/my-frontend:latest \
            frontend

      # 5. Publicar la imagen al registry
      - name: Push Docker image for Frontend
        run: |
          docker push robertorg/my-frontend:latest
