name: Build and Push SQL Docker Image

on:
  push:
    branches:
      - main # Se ejecutará al hacer push a la rama 'main'

jobs:
  build-sql-db:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3 # Acción oficial de GitHub para extraer el repositorio

      # 2. Configurar Buildx (Buildx permite usar Docker BuildKit)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Configura Buildx para Docker

      # 3. Log in en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Usa tu Docker Hub username guardado en Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Usa tu Docker Hub password guardado en Secrets

      # 4. Construir la imagen usando el Dockerfile para la base de datos SQL
      - name: Build Docker image for SQL Database
        run: |
          docker build \
            --file sql/Dockerfile \  # Especifica el Dockerfile que usas para la base de datos SQL
            --tag robertorg/sql-database:latest \  # Nombre y etiqueta de la imagen
            sql  # El directorio donde se encuentra tu Dockerfile

      # 5. Publicar la imagen en Docker Hub
      - name: Push Docker image for SQL Database
        run: |
          docker push robertorg/sql-database:latest  # Publica la imagen en Docker Hub
