name: Build and Push SQL Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir y publicar la imagen
      - name: Build and push SQL image
        uses: docker/build-push-action@v5
        with:
          context: db
          file: db/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sql-database:latest



