name: Build and Push SQL Docker Image

on:
  push:
    branches:
      - main  # Se ejecutar치 al hacer push a la rama 'main'

jobs:
  build-sql-db:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c칩digo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Buildx (Buildx permite usar Docker BuildKit)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construir la imagen usando el Dockerfile que est치 en db/
      - name: Build Docker image for SQL Database
        run: |
          docker build \
            -f db/Dockerfile \         # Ruta al Dockerfile dentro de db/
            -t ${{ secrets.DOCKER_USERNAME }}/sql-database:latest \  # Etiqueta de la imagen
            db                            # Contexto de construcci칩n: la carpeta db/

      # 5. Publicar la imagen en Docker Hub
      - name: Push Docker image for SQL Database
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sql-database:latest


